### ISSUE TITLE
Modify the LED pin for other boards

### ISSUE THREAD

**Issue by jamesle-0812** [dhylands/stm32-test#1]
Hi there, I'm very interested in your work. I'd love to upload my code on vscode thru USB without USB to Serial adapter or ST-link 2. Recently I have a board based on STM32F103 but the LED pin is PA8. It also has an user button on PA1. How can I modify your code to work with my board? Thanks again for your time and your awesome work!

**Comment by davehylands** [comment]
In order to use USB without a USB-to-serial adapter, you'll need a USB DFU bootloader. The one I used can be found here: https://github.com/dhylands/libopencm3-examples/tree/generic-stmf103/examples/stm32/f1/other/usb_dfu There is a compiled version (for the blue pill STMF103 board here: https://github.com/dhylands/stm32-test/tree/master/board-STM32F103-Mini) This will work if you have the same frequency crystal as the blue pill, otherwise you;'ll need to build one yourself.

This needs to be uploaded using the STMF103's builtin serial bootloader.

The LED is configured here: https://github.com/dhylands/stm32-test/blob/master/board-STM32F103-Mini/config.h

I don't think that there is any button support in the current code, so you'll need to add that yourself.

**Comment by jamesle-0812** [comment]
Thanks for your reply. I have another question. I've followed your instructions to flash your bootloader and then upload a test code (used to blink built-in led) based on Arduino framework thru dfu-util, it works well. However, when I change the framework to libopencm3 or Mbed with similar test code, it doesn't work properly. On the cmd, it shows up "Upload successfully" but the led doesn't blink. All the codes are built by vscode + platformio. Do I need to add any library to the test code to make it works with your bootloader? Thanks in advance!

**Comment by dhylands** [comment]
The big thing that has to change is that when you’re using the boot loader, you need to change the base address of the code from 0x8000000 to 0x8002000 like this:  https://github.com/dhylands/stm32-test/blob/master/board-STM32F103-Mini/STM32F103RBTx_FLASH.ld#L44

**Comment by jamesle-0812** [comment]
Awesome. After following your hint, I've configured a link script in platformio and then it works like a charm. Much appreciate your help. Wish you all the best!

**Comment by jamesle-0812** [comment]
Just let you know that the dfu binary file works well with libopencm3 and Mbed framework, at least with blink led code. On CMSIS, HAL & LL, SPL (with little bit change), it has no luck although I've tried using your linker script as well as changing app address in their default linker scripts. If you have any advice, please let me know. Otherwise nevermind. Have a good day!

**Comment by davehylands** [comment]
It’s probably still something address related, but it’s really hard to say
what assumptions the other frameworks have. I like to check the linker map
file to look for clues.

There probably needs to be some changes to support moving the ISR table as
well. The NVIC defaults to 0x8000000 and needs to be reprogrammed to work
with a vector table at 0x8020000

**Comment by jamesle-0812** [comment]
Your guess may be true. My blink LED code is based on system interrupt (SysTick) and it doesn't work. I've tested another code with USART1 interrupt and got the same result. However, TIM2 interrupt works fine.
Please let me know if you do an update version!
